refactor: pull out caching of node-modules to workflow (#361)
* refactor: simplify download-data check

* refactor: eliminate need for uuid action

* refactor: remove uuid action

* chore: add debug console

* chore: remove partial restore keys for download data

* fix: remove unneeded console

* feat: use only exact key for node modules

* feat: add link directly to deploy job when deploy starts

* refactor: adjust language of deploy messages

* chore: add basic combo changelog post

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,10 +28,6 @@ jobs:
         with:
           node-version: 16
 
-      - name: Create Workflow ID 🆔
-        id: generate-uuid
-        uses: filipstefansson/uuid-action@v1
-
       - name: Cache node modules 🗃
         id: cache-nodemodules
         uses: actions/cache@v3
@@ -44,12 +40,14 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install Node Modules 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
         run: npm ci
+
+      - name: Create Workflow ID 🆔
+        id: generate-uuid
+        run: npm run workflow:create-workflow-id
 
       - name: Cache Downloaded Data ⏬
         id: cache-downloaded-data
@@ -61,8 +59,6 @@ jobs:
             frontend/static/api/combo-data.json
             frontend/static/changelog.json
           key: ${{ runner.os }}-download-data-${{ steps.generate-uuid.outputs.uuid }}
-          restore-keys: |
-            ${{ runner.os }}-download-data-
 
       - name: Download Data ⬇️
         if: steps.cache-downloaded-data.outputs.cache-hit != 'true'
@@ -104,8 +100,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -121,21 +115,10 @@ jobs:
             frontend/static/api/combo-data.json
             frontend/static/changelog.json
           key: ${{ runner.os }}-download-data-${{ needs.setup.outputs.workflow_id }}
-          restore-keys: |
-            ${{ runner.os }}-download-data-
 
-      - name: Download Data ⬇️
+      - name: Check Downloaded Data Cache ⬇️
         if: steps.cache-downloaded-data.outputs.cache-hit != 'true'
-        env:
-          NODE_ENV: production
-          FIREBASE_DEPLOYMENT_TOKEN: ${{ secrets.FIREBASE_DEPLOYMENT_TOKEN }}
-          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
-          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
-          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
-          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
-          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
-          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
-        run: npm run download-data
+        run: echo "Downloaded data cache failed"; exit 1;
 
       - name: Compare Changelog 🪵
         id: changelog_result
@@ -162,8 +145,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -193,8 +174,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -210,21 +189,10 @@ jobs:
             frontend/static/api/combo-data.json
             frontend/static/changelog.json
           key: ${{ runner.os }}-download-data-${{ needs.setup.outputs.workflow_id }}
-          restore-keys: |
-            ${{ runner.os }}-download-data-
 
-      - name: Download Data ⬇️
+      - name: Check Downloaded Data Cache ⬇️
         if: steps.cache-downloaded-data.outputs.cache-hit != 'true'
-        env:
-          NODE_ENV: production
-          FIREBASE_DEPLOYMENT_TOKEN: ${{ secrets.FIREBASE_DEPLOYMENT_TOKEN }}
-          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
-          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
-          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
-          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
-          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
-          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
-        run: npm run download-data
+        run: echo "Downloaded data cache failed"; exit 1;
 
       - name: Run unit tests 🧪
         run: npm test
@@ -250,8 +218,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -267,21 +233,10 @@ jobs:
             frontend/static/api/combo-data.json
             frontend/static/changelog.json
           key: ${{ runner.os }}-download-data-${{ needs.setup.outputs.workflow_id }}
-          restore-keys: |
-            ${{ runner.os }}-download-data-
 
-      - name: Download Data ⬇️
+      - name: Check Downloaded Data Cache ⬇️
         if: steps.cache-downloaded-data.outputs.cache-hit != 'true'
-        env:
-          NODE_ENV: production
-          FIREBASE_DEPLOYMENT_TOKEN: ${{ secrets.FIREBASE_DEPLOYMENT_TOKEN }}
-          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
-          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
-          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
-          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
-          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
-          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
-        run: npm run download-data
+        run: echo "Downloaded data cache failed"; exit 1;
 
       - name: Run Integration tests 💻
         run: npm run test:integration
@@ -313,8 +268,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -349,8 +302,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
@@ -366,21 +317,10 @@ jobs:
             frontend/static/api/combo-data.json
             frontend/static/changelog.json
           key: ${{ runner.os }}-download-data-${{ needs.setup.outputs.workflow_id }}
-          restore-keys: |
-            ${{ runner.os }}-download-data-
 
-      - name: Download Data ⬇️
+      - name: Check Downloaded Data Cache ⬇️
         if: steps.cache-downloaded-data.outputs.cache-hit != 'true'
-        env:
-          NODE_ENV: production
-          FIREBASE_DEPLOYMENT_TOKEN: ${{ secrets.FIREBASE_DEPLOYMENT_TOKEN }}
-          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
-          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
-          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
-          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
-          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
-          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
-        run: npm run download-data
+        run: echo "Downloaded data cache failed"; exit 1;
 
       - name: Send Deploy Start Notification ✉️
         run: npm run discord-webhook:start-deploy
@@ -441,8 +381,6 @@ jobs:
             ~/.npm
             ~/.cache
           key: ${{ runner.os }}-node-modules-build-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-build-
 
       - name: Install 📦
         if: steps.cache-nodemodules.outputs.cache-hit != 'true'
